name: ExplodingUnbreakables
main: jasonwynn10\EU\Main
version: 0.1.0
api:
 3.1.1
description: "A plugin which allows for bedrock to be blown up after tnt explodes a certain number of times"
author: "jasonwynn10"